services:
  moment:
    build:
      context: .
      dockerfile: Dockerfile
    image: ruida/moment:2.0
    container_name: moment
    restart: always
    volumes:
      - .moment:/app/data
    ports:
      - 9999:9999