services:
  moment:
    build:
      context: .
      dockerfile: Dockerfile
    image: moment:go
    container_name: moment
    restart: always
    volumes:
      - .moment:/app/data
    ports:
      - 9999:9999
    environment:
      MOMENT_COOKIE_SECURE: ${MOMENT_COOKIE_SECURE:-false}
