CREATE TABLE IF NOT EXISTS user (
 id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, username VARCHAR(20) NOT NULL UNIQUE,
 alias VARCHAR(30), email VARCHAR(255) NOT NULL UNIQUE, avatar VARCHAR(255) NOT NULL,
 password VARCHAR(255), last_login TIMESTAMP, remark JSON
);
CREATE TABLE IF NOT EXISTS setting (
 id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, general JSON NOT NULL,
 meta JSON NOT NULL, content JSON NOT NULL, storage JSON NOT NULL
);
CREATE TABLE IF NOT EXISTS category (
 id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, name VARCHAR(30) NOT NULL, alias VARCHAR(50) NOT NULL,
 desc TEXT, "order" INT NOT NULL DEFAULT 0, parent_id INT NOT NULL DEFAULT 0, remark JSON
);
CREATE TABLE IF NOT EXISTS blog (
 id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, title VARCHAR(50) NOT NULL, desc TEXT,
 location TEXT, time TIMESTAMP, is_hidden INT NOT NULL DEFAULT 0, remark JSON
);
CREATE TABLE IF NOT EXISTS blog_image (
 id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, image_url TEXT NOT NULL, title VARCHAR(50),
 desc TEXT, location TEXT, is_hidden INT NOT NULL DEFAULT 0, metadata TEXT, time TIMESTAMP,
 "order" INT NOT NULL DEFAULT 0, blog_id BIGINT NOT NULL REFERENCES blog(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS blog_category (
 blog_id BIGINT NOT NULL REFERENCES blog(id) ON DELETE CASCADE,
 category_id BIGINT NOT NULL REFERENCES category(id) ON DELETE CASCADE
);
