package moment

import (
	"bytes"
	"crypto/sha256"
	"database/sql"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// Generated by Python argon2-cffi, independent of the Go password implementation.
const legacyHash = "$argon2id$v=19$m=65536,t=3,p=4$OSjMlylPxAMrEI3PMlr06g$FafqcNe/4nELPXow2Xao2eigIOPDt4APfq2nEd/Iyu0"
const testPassword = "CompatibilityTest!2026"

func testApp(t *testing.T) (*App, http.Handler, *http.Cookie) {
	t.Helper()
	a, err := Open(t.TempDir(), t.TempDir(), false)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { a.Close() })
	if _, err = a.db.Exec("INSERT INTO user(username,email,avatar,password) VALUES ('tester','test@example.com','',?)", legacyHash); err != nil {
		t.Fatal(err)
	}
	token := strings.Repeat("a", 64)
	if _, err = a.db.Exec("INSERT INTO moment_sessions VALUES (?,1,?)", tokenDigest(token), time.Now().Add(time.Hour).Unix()); err != nil {
		t.Fatal(err)
	}
	return a, a.Router(), &http.Cookie{Name: "moment_session", Value: token}
}
func call(t *testing.T, h http.Handler, method, path string, body any, cookie *http.Cookie) (*httptest.ResponseRecorder, Object) {
	t.Helper()
	var input io.Reader
	if body != nil {
		data, err := json.Marshal(body)
		if err != nil {
			t.Fatal(err)
		}
		input = bytes.NewReader(data)
	}
	r := httptest.NewRequest(method, path, input)
	r.Header.Set("Content-Type", "application/json")
	if cookie != nil {
		r.AddCookie(cookie)
	}
	w := httptest.NewRecorder()
	h.ServeHTTP(w, r)
	var result Object
	if err := json.Unmarshal(w.Body.Bytes(), &result); err != nil {
		t.Fatalf("invalid JSON response for %s", path)
	}
	return w, result
}
func status(t *testing.T, w *httptest.ResponseRecorder, want int) {
	t.Helper()
	if w.Code != want {
		t.Fatalf("HTTP status: got %d, want %d: %s", w.Code, want, w.Body.String())
	}
}
func seedPost(t *testing.T, a *App, title string, hidden, imageHidden bool) (int64, int64) {
	t.Helper()
	r, err := a.db.Exec("INSERT INTO blog(title,is_hidden,remark) VALUES (?,?, '{\"preserve\":true}')", title, hidden)
	if err != nil {
		t.Fatal(err)
	}
	id, _ := r.LastInsertId()
	r, err = a.db.Exec("INSERT INTO blog_image(blog_id,image_url,is_hidden) VALUES (?,'https://example.com/photo.jpg',?)", id, imageHidden)
	if err != nil {
		t.Fatal(err)
	}
	img, _ := r.LastInsertId()
	return id, img
}
func TestLegacyPasswordAndSessionLifecycle(t *testing.T) {
	a, h, cookie := testApp(t)
	if !verifyPassword(testPassword, legacyHash) || verifyPassword("wrong", legacyHash) || verifyPassword(testPassword, "$argon2id$invalid") {
		t.Fatal("legacy password compatibility failed")
	}
	w, _ := call(t, h, "GET", "/api/admin/me", nil, nil)
	status(t, w, 401)
	r := httptest.NewRequest("GET", "/api/admin/me", nil)
	r.Header.Set("token", "dev")
	w = httptest.NewRecorder()
	h.ServeHTTP(w, r)
	status(t, w, 401)
	w, _ = call(t, h, "POST", "/api/admin/login", Object{"username": "tester", "password": testPassword}, nil)
	status(t, w, 200)
	logged := w.Result().Cookies()[0]
	if !logged.HttpOnly || logged.SameSite != http.SameSiteStrictMode || logged.Value == "" {
		t.Fatal("unsafe session cookie")
	}
	w, result := call(t, h, "GET", "/api/admin/me", nil, logged)
	status(t, w, 200)
	if _, found := object(result["data"])["password"]; found {
		t.Fatal("password disclosed")
	}
	r = httptest.NewRequest("PATCH", "/api/admin/settings/meta", strings.NewReader(`{"site_name":"attack"}`))
	r.AddCookie(logged)
	r.Header.Set("Content-Type", "application/json")
	r.Header.Set("Origin", "https://attacker.example")
	w = httptest.NewRecorder()
	h.ServeHTTP(w, r)
	status(t, w, 403)
	w, _ = call(t, h, "POST", "/api/admin/me/password", Object{"old_password": testPassword, "new_password": "NewPassword!2026"}, logged)
	status(t, w, 200)
	w, _ = call(t, h, "GET", "/api/admin/me", nil, logged)
	status(t, w, 401)
	w, _ = call(t, h, "GET", "/api/admin/me", nil, cookie)
	status(t, w, 401)
	w, _ = call(t, h, "POST", "/api/admin/login", Object{"username": "tester", "password": testPassword}, nil)
	status(t, w, 401)
	w, _ = call(t, h, "POST", "/api/admin/login", Object{"username": "tester", "password": "NewPassword!2026"}, nil)
	status(t, w, 200)
	logged = w.Result().Cookies()[0]
	w, _ = call(t, h, "POST", "/api/admin/logout", Object{}, logged)
	status(t, w, 200)
	w, _ = call(t, h, "GET", "/api/admin/me", nil, logged)
	status(t, w, 401)
	_, err := a.db.Exec("UPDATE moment_sessions SET expires_at=0")
	if err != nil {
		t.Fatal(err)
	}
}
func TestAtomicPostUpdatesAndVisibility(t *testing.T) {
	a, h, cookie := testApp(t)
	id, img := seedPost(t, a, "Original", false, false)
	_, otherImg := seedPost(t, a, "Hidden image", false, true)
	seedPost(t, a, "Hidden post", true, false)
	if _, err := a.db.Exec("INSERT INTO category(name,alias,parent_id) VALUES ('Parent','parent',0),('Child','child',1)"); err != nil {
		t.Fatal(err)
	}
	if _, err := a.db.Exec("INSERT INTO blog_category VALUES (?,1)", id); err != nil {
		t.Fatal(err)
	}
	body := PostInput{Title: "Changed", Images: []ImageInput{{ID: img, URL: "https://example.com/new.jpg"}, {ID: otherImg, URL: "https://example.com/foreign.jpg"}}, Categories: []int64{2}}
	w, _ := call(t, h, "PUT", fmt.Sprintf("/api/admin/posts/%d", id), body, cookie)
	status(t, w, 400)
	var title, url string
	var categories int
	a.db.QueryRow("SELECT title FROM blog WHERE id=?", id).Scan(&title)
	a.db.QueryRow("SELECT image_url FROM blog_image WHERE id=?", img).Scan(&url)
	a.db.QueryRow("SELECT COUNT(*) FROM blog_category WHERE blog_id=? AND category_id=1", id).Scan(&categories)
	if title != "Original" || url != "https://example.com/photo.jpg" || categories != 1 {
		t.Fatal("failed save partially changed original post")
	}
	body.Images = body.Images[:1]
	body.Images = append(body.Images, ImageInput{URL: "/uploads/new.png", Hidden: true})
	w, _ = call(t, h, "PUT", fmt.Sprintf("/api/admin/posts/%d", id), body, cookie)
	status(t, w, 200)
	var preserved int
	var remark string
	a.db.QueryRow("SELECT COUNT(*) FROM blog_image WHERE id=? AND blog_id=?", img, id).Scan(&preserved)
	a.db.QueryRow("SELECT remark FROM blog WHERE id=?", id).Scan(&remark)
	if preserved != 1 || remark != "{\"preserve\":true}" {
		t.Fatal("existing IDs or imported remark changed")
	}
	a.db.QueryRow("SELECT COUNT(*) FROM blog_category WHERE blog_id=?", id).Scan(&categories)
	if categories != 2 {
		t.Fatal("child category did not include parent")
	}
	w, result := call(t, h, "GET", "/api/v1/visitor/blog/list?page=1&page_size=1", nil, nil)
	status(t, w, 200)
	if integer(result["total"]) != 1 || len(result["data"].([]any)) != 1 || len(object(result["data"].([]any)[0])["images"].([]any)) != 1 {
		t.Fatal("public pagination included hidden posts or images")
	}
	w, _ = call(t, h, "GET", "/api/admin/posts?order=title%3BDROP%20TABLE%20blog", nil, cookie)
	status(t, w, 400)
	w, _ = call(t, h, "DELETE", fmt.Sprintf("/api/admin/posts/%d", id), nil, cookie)
	status(t, w, 200)
	a.db.QueryRow("SELECT COUNT(*) FROM blog_image WHERE blog_id=?", id).Scan(&preserved)
	if preserved != 2 {
		t.Fatal("moving to trash did not preserve post images")
	}
	w, result = call(t, h, "GET", "/api/admin/trash", nil, cookie)
	status(t, w, 200)
	trashed := object(result["data"].([]any)[0])
	w, _ = call(t, h, "POST", "/api/admin/trash/batch", Object{"action": "purge", "confirm": true, "targets": []Object{{"id": id, "revision": trashed["revision"]}}}, cookie)
	status(t, w, 200)
	a.db.QueryRow("SELECT COUNT(*) FROM blog_image WHERE blog_id=?", id).Scan(&preserved)
	if preserved != 0 {
		t.Fatal("permanent deletion did not cascade images")
	}
}
func TestSettingsPreserveCredentialsAndCategoryHierarchy(t *testing.T) {
	a, h, cookie := testApp(t)
	_, err := a.db.Exec(`UPDATE setting SET storage='{"endpoint":"https://s3.example.com","access_id":"private-id","secret_key":"private-secret","unknown":{"kept":true},"max_size":32}'`)
	if err != nil {
		t.Fatal(err)
	}
	w, _ := call(t, h, "GET", "/api/admin/settings", nil, cookie)
	status(t, w, 200)
	if strings.Contains(w.Body.String(), "private-id") || strings.Contains(w.Body.String(), "private-secret") {
		t.Fatal("storage credentials disclosed")
	}
	w, _ = call(t, h, "GET", "/api/v1/visitor/settings/storage", nil, nil)
	status(t, w, 404)
	w, _ = call(t, h, "PATCH", "/api/admin/settings/storage", Object{"access_id": "", "secret_key": "", "max_size": 64}, cookie)
	status(t, w, 200)
	s, _ := a.readSettings()
	storage := object(s["storage"])
	if storage["access_id"] != "private-id" || storage["secret_key"] != "private-secret" || object(storage["unknown"])["kept"] != true {
		t.Fatal("masked credentials or unknown settings lost")
	}
	w, result := call(t, h, "POST", "/api/admin/categories", Object{"name": "照片", "alias": "照片", "parent_id": 0}, cookie)
	status(t, w, 200)
	parent := integer(object(result["data"])["id"])
	w, result = call(t, h, "POST", "/api/admin/categories", Object{"name": "旅途", "alias": "travel", "parent_id": parent}, cookie)
	status(t, w, 200)
	child := integer(object(result["data"])["id"])
	w, _ = call(t, h, "PUT", fmt.Sprintf("/api/admin/categories/%d", parent), Object{"name": "照片", "alias": "照片", "parent_id": child}, cookie)
	status(t, w, 400)
	w, _ = call(t, h, "DELETE", fmt.Sprintf("/api/admin/categories/%d", parent), nil, cookie)
	status(t, w, 409)
}
func TestLocalUploadValidation(t *testing.T) {
	a, h, cookie := testApp(t)
	post := func(filename string, content []byte) *httptest.ResponseRecorder {
		var data bytes.Buffer
		form := multipart.NewWriter(&data)
		part, _ := form.CreateFormFile("file", filename)
		part.Write(content)
		form.Close()
		r := httptest.NewRequest("POST", "/api/admin/uploads", &data)
		r.Header.Set("Content-Type", form.FormDataContentType())
		r.AddCookie(cookie)
		w := httptest.NewRecorder()
		h.ServeHTTP(w, r)
		return w
	}
	w := post("photo.png", []byte("not an image"))
	status(t, w, 400)
	png := []byte{137, 80, 78, 71, 13, 10, 26, 10}
	png = append(png, make([]byte, 64)...)
	w = post("../../photo.png", png)
	status(t, w, 200)
	var result Object
	json.Unmarshal(w.Body.Bytes(), &result)
	url := text(object(result["data"])["image_url"])
	if !strings.HasPrefix(url, "/uploads/") || strings.Contains(url, "..") {
		t.Fatal("unsafe upload path")
	}
	if _, err := os.Stat(filepath.Join(a.data, strings.TrimPrefix(url, "/"))); err != nil {
		t.Fatal("uploaded file missing")
	}
}

func TestS3UploadUsesLegacySettings(t *testing.T) {
	a, h, cookie := testApp(t)
	var received bool
	remote := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != "PUT" || !strings.HasPrefix(r.URL.Path, "/test-bucket/2026/") || r.Header.Get("Content-Type") != "image/png" || !strings.Contains(r.Header.Get("Authorization"), "test-access") {
			t.Errorf("unexpected S3 request shape")
		}
		payload, _ := io.ReadAll(r.Body)
		if len(payload) == 0 {
			t.Errorf("empty S3 upload")
		}
		received = true
		w.Header().Set("ETag", `"test-etag"`)
		w.WriteHeader(200)
	}))
	defer remote.Close()
	storage, _ := json.Marshal(Object{"enable_storage": true, "endpoint": remote.URL, "region": "us-east-1", "bucket": "test-bucket", "access_id": "test-access", "secret_key": "test-secret", "prefix": "https://photos.example.com", "path": "2026/{month}/{filename}", "max_size": 32})
	if _, err := a.db.Exec("UPDATE setting SET storage=?", string(storage)); err != nil {
		t.Fatal(err)
	}
	var input bytes.Buffer
	form := multipart.NewWriter(&input)
	part, _ := form.CreateFormFile("file", "photo.png")
	part.Write(append([]byte{137, 80, 78, 71, 13, 10, 26, 10}, make([]byte, 64)...))
	form.Close()
	r := httptest.NewRequest("POST", "/api/admin/uploads", &input)
	r.Header.Set("Content-Type", form.FormDataContentType())
	r.AddCookie(cookie)
	w := httptest.NewRecorder()
	h.ServeHTTP(w, r)
	status(t, w, 200)
	if !received || !strings.Contains(w.Body.String(), "https://photos.example.com/2026/") {
		t.Fatal("legacy S3 configuration not used")
	}
}

// Opt-in compatibility check: copy a SQLite backup into a temporary directory;
// never open or migrate the supplied source for writing, never print its rows.
func TestProductionSnapshotCompatibility(t *testing.T) {
	source := os.Getenv("MOMENT_TEST_DATABASE")
	if source == "" {
		t.Skip("set MOMENT_TEST_DATABASE to a consistent SQLite backup")
	}
	data := t.TempDir()
	destination := filepath.Join(data, "db.sqlite3")
	in, err := os.Open(source)
	if err != nil {
		t.Fatal(err)
	}
	defer in.Close()
	out, err := os.Create(destination)
	if err != nil {
		t.Fatal(err)
	}
	_, err = io.Copy(out, in)
	out.Close()
	if err != nil {
		t.Fatal(err)
	}
	db, err := sql.Open("sqlite", destination)
	if err != nil {
		t.Fatal(err)
	}
	tables, err := query(db, "SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
	if err != nil {
		t.Fatal(err)
	}
	digests := map[string][32]byte{}
	for _, table := range tables {
		name := text(table["name"])
		rows, e := query(db, `SELECT * FROM "`+strings.ReplaceAll(name, `"`, `""`)+`" ORDER BY rowid`)
		if e != nil {
			t.Fatal(e)
		}
		b, _ := json.Marshal(rows)
		digests[name] = sha256.Sum256(b)
	}
	db.Close()
	a, err := Open(data, t.TempDir(), false)
	if err != nil {
		t.Fatal(err)
	}
	for _, table := range tables {
		name := text(table["name"])
		var schema string
		if err = a.db.QueryRow("SELECT sql FROM sqlite_master WHERE name=?", name).Scan(&schema); err != nil {
			t.Fatal(err)
		}
		if schema != table["sql"] {
			t.Fatalf("original schema changed: %s", name)
		}
		rows, e := query(a.db, `SELECT * FROM "`+strings.ReplaceAll(name, `"`, `""`)+`" ORDER BY rowid`)
		if e != nil {
			t.Fatal(e)
		}
		b, _ := json.Marshal(rows)
		if sha256.Sum256(b) != digests[name] {
			t.Fatalf("original rows changed: %s", name)
		}
	}
	backups, _ := filepath.Glob(filepath.Join(data, "backups", "*.sqlite3"))
	if len(backups) != 1 {
		t.Fatal("pre-migration snapshot missing")
	}
	w, _ := call(t, a.Router(), "GET", "/api/v1/visitor/blog/list?page_size=100", nil, nil)
	status(t, w, 200)
	a.Close()
	a, err = Open(data, t.TempDir(), false)
	if err != nil {
		t.Fatal(err)
	}
	defer a.Close()
	backups, _ = filepath.Glob(filepath.Join(data, "backups", "*.sqlite3"))
	if len(backups) != 1 {
		t.Fatal("migration was not idempotent")
	}
	var integrity string
	a.db.QueryRow("PRAGMA integrity_check").Scan(&integrity)
	if integrity != "ok" {
		t.Fatal("integrity check failed")
	}
}
